///usr/bin/[ "$0".bin -nt "$0" ] || cc -Wall ${CFLAGS:--g -Og} ${LDFLAGS} "$0" -o "$0".bin <<EOSHELL || exit 1; driver="$1"; shift; exec "$0".bin "$(which "$driver")" "$@"; exit 42
#ifdef EOSHELL
$(
    # The top half of this file is a shell script.
    # The bottom half is a C program.
    # The output of the shell script will be available to the C preprocessor when compiling
    # the C program.
    # The hash-bang line above arranges that executing this file will compile if necessary,
    # then (always) run the C code.

    # Overall, this pattern fulfils the same purpoes as "configure && make && ./a.out"
    # but packaged as a single file that one can chmod +x and then execute directly.

    # This is pretty much arbitrary shell code, but the preprocessor will warn (harmlessly)
    # when our lines do not have properly matched single or double quotes. Some shell
    # idioms, like multi-line quoted strings, break this expectation and provoke a warning.
    # Also, we must not begin any line with [[:blank:]]*#[[:blank:]]*(if|else|elif|endif).

	# The output of this shell code is available to the C compiler by #including "/dev/stdin"
    # i.e. if it outputs something it should output C code.

    # To source any shell functions for testing, a good approach is:
    # source <( sed -n '/^\$($/,/STOP\ SOURCING/ p' ccwrap.c | tail -n+2 | head -n-1 )

    # STOP SOURCING HERE <-- leave this in place for the 'source' recipe (in comment above)
    # (I used to make it match ')' by itself, but that will also source any non-function
    # imperative code in the script... put such code below this comment.)
)
#else
#define EOSHELL
#endif
EOSHELL
// From here on we are in plain C and will never be run by the shell.
#undef NDEBUG  /* assert() must not be a no-op */
#define _GNU_SOURCE
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <strings.h> /* for bzero() */
#include <err.h>
#include <errno.h>
#include <assert.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <ctype.h>
#include "/dev/stdin" /* include whatever was generated by shell script above */
#ifdef _LIBGEN_H
#error "libgen got included? we don't work with POSIX basename()..."
#endif

// source "$(dirname "${BASH_SOURCE[0]}")"/../wrapper/bin/elap.bash-v2 trap
// usage: ccwrap compiler <options...>
// e.g.   ccwrap gcc -o /tmp/hello /tmp/hello.c

// What do we do?
// 1. parse the -### output into commands as lists of words (shell array variables)
// 2. substitute subcommands as necessary -- this is really for our extender to do
// 3. lift subcommands back to driver invocations

// snarf the wrapper functions
// HACK: we use the old version
// we use write_cc_options_from_cc1_command
// . "$(dirname "${BASH_SOURCE[0]}")"/../wrapper/lib/wrapper-funcs.sh
// ---------------------------------
static int debug_level;
FILE *debug_stream;
int debug_println(int level, const char *fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	int ret;
	if (debug_level >= level) {
		ret = vfprintf(debug_stream ?: stderr, fmt, ap);
		fputc('\n', debug_stream ?: stderr);
	} else ret = 0;
	va_end(ap);
	return ret;
}
#define die(str) \
	assert(0 && str)

_Bool not_really_traditional;

struct args
{
	int argc;
	char **argv;
};
#define APPEND3(ctr, vec, str) do { \
	++ctr; \
	vec = realloc(vec, (1 + ctr) * sizeof(char*)); \
	if (!vec) die("could not allocate memory (resizing an argv)"); \
	vec[ctr - 1] = str; \
	vec[ctr] = NULL; \
} while (0)

#define APPEND(av, str) APPEND3((av).argc, (av).argv, str)

#define EQUAL(str1, str2) (0 == strcmp(str1, str2))
#define HAS_PREFIX(str1, pref) ({ \
    size_t len = strlen(pref); \
    0 == strncmp(str1, pref, len) && str1[len] != '\0'; /* don't match if the suffix is empty */ \
})

/* Now for EQUAL_ANY and HAS_PREFIX_ANY...
 * first some canonical Cloak-style preprocessor definitions. */
#define CAT(a, ...) PRIMITIVE_CAT(a, __VA_ARGS__)
#define PRIMITIVE_CAT(a, ...) a ## __VA_ARGS__
#define EVAL(...)  EVAL1(EVAL1(EVAL1(__VA_ARGS__)))
#define EVAL1(...) EVAL2(EVAL2(EVAL2(__VA_ARGS__)))
#define EVAL2(...) EVAL3(EVAL3(EVAL3(__VA_ARGS__)))
#define EVAL3(...) EVAL4(EVAL4(EVAL4(__VA_ARGS__)))
#define EVAL4(...) EVAL5(EVAL5(EVAL5(__VA_ARGS__)))
#define EVAL5(...) __VA_ARGS__
#define EMPTY()
#define DEFER(id) id EMPTY()
#define OBSTRUCT(...) __VA_ARGS__ DEFER(EMPTY)()
#define EAT(...)

/* We will use a recursive style where the base case is the 1-case.  */
#define IF_HAS_ONLY_ONE(...) \
  /* how to write this? shift a sequence of N right by #args, then pick the Nth */ \
  THIRTYSIXTH(__VA_ARGS__, /* 35 things: */ EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, EAT, PRIMITIVE_CAT)
#define IF_HAS_MULTIPLE(...) \
  THIRTYSIXTH(__VA_ARGS__, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, PRIMITIVE_CAT, EAT)
#define THIRTYSIXTH(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, N, ...) N

/* Now our recursive(!) definition of EQUAL_ANY */
#define EQUAL_ANY_(str, str1, strs...) ( \
   EQUAL(str, str1) || \
   IF_HAS_ONLY_ONE(strs)( EQUAL(str, strs) ) \
   IF_HAS_MULTIPLE(strs)( OBSTRUCT(EQUAL_ANY_INDIRECT)()(str, strs) ) ) /* FIXME: obstruct/indirect etc. */
#define EQUAL_ANY_INDIRECT() EQUAL_ANY_
#define EQUAL_ANY(...) EVAL(EQUAL_ANY_(__VA_ARGS__))

/* Now our recursive(!) definition of HAS_PREFIX_ANY */
#define HAS_PREFIX_ANY_(str, str1, strs...) ( \
   HAS_PREFIX(str, str1) || \
   IF_HAS_ONLY_ONE(strs)( HAS_PREFIX(str, strs) ) \
   IF_HAS_MULTIPLE(strs)( OBSTRUCT(HAS_PREFIX_ANY_INDIRECT)()(str, strs) ) ) /* FIXME: obstruct/indirect etc. */
#define HAS_PREFIX_ANY_INDIRECT() HAS_PREFIX_ANY_
#define HAS_PREFIX_ANY(...) EVAL(HAS_PREFIX_ANY_(__VA_ARGS__))

struct normalization_result
{
	char **saw_E;
	char **saw_Os;
	char **saw_Werror;
	char **saw_D_FORTIFY_SOURCE;
	char **saw_o;
	unsigned opos_D_FORTIFY_SOURCE;
	unsigned infiles_count;
	char **infiles_names;
};
// We run a normalizing pass on a cc1 command, to remove some awkward forms from it.
// NOTE: normalizing cc1 options does not remove the nasty "-MD <argument>" form.
//
// What does it do?
// It tries to enumerate input files, but is very imprecise at present.
// It identifies the output file, pulling out "-o" and then re-adding it (pointlessly).
//
// The main purpose is to rewrite cases where a single cc1 invocation works, but
// splitting into separate preprocessing and compilation invocations doesn't.
// The main thing currently is to futz with options to avoid a breaking interaction
// between -Werror, -D_FORTIFY_SOURCE and -Os.
struct args normalize_cc1_argv(struct args *in, struct normalization_result *res)
{
	struct args out = { .argc = 0, .argv = NULL };
	/* our shell loop iterated over $1.., where $0 was the cc1 command, and
	 * wrote output infiles[0..] and norm_cc1_options[0..]
	 * but this was immediately corrected in its caller by prepending the cc1 command.
	 * We instead copy the cc1 command. */
	assert(in->argc > 0);
	APPEND(out, in->argv[0]);
	for (unsigned i = 1; i < in->argc; ++i)
	{
		debug_println(2, "args remaining %d, argv[i] is `%s'", in->argc - i, in->argv[i]);
		if (EQUAL(in->argv[i], "-o"))
		{
			if (i+1 == in->argc) { die("refusing to process argvec ending with `-o'"); }
			res->saw_o = &in->argv[i];
			++i; // skip one
			continue; // we do not snarf this; caller must inspect saw_o
		}
		if (EQUAL(in->argv[i], "-E"))
		{
			res->saw_E = &in->argv[i];
			goto snarf;
		}
		if (EQUAL(in->argv[i], "-Os"))
		{
			res->saw_Os = &in->argv[i];
			goto snarf;
		}
		if (EQUAL(in->argv[i], "-Werror"))
		{
			res->saw_Werror = &in->argv[i];
			goto snarf;
		}
		if (EQUAL(in->argv[i], "-D_FORTIFY_SOURCE") || HAS_PREFIX(in->argv[i], "-D_FORTIFY_SOURCE="))
		{
			res->saw_D_FORTIFY_SOURCE = &in->argv[i];
			res->opos_D_FORTIFY_SOURCE = out.argc;
			goto snarf;
		}
		if (EQUAL(in->argv[i-1], "-D") && (
			EQUAL(in->argv[i], "_FORTIFY_SOURCE") || HAS_PREFIX(in->argv[i], "_FORTIFY_SOURCE=")
		))
		{
			res->opos_D_FORTIFY_SOURCE = out.argc - 1;
			goto snarf;
		}
		if (EQUAL(in->argv[i], "-"))
		{
			APPEND3(res->infiles_count, res->infiles_names, "-");
			goto snarf;
		}
		snarf:
		if (in->argv[i][0] != '-')
		{
			// FIXME: this is super-imprecise.
			// A useful regex for scraping the gcc man page for opts-with-args:
			// -[-a-z0-9]+ [^-[:blank:]]
			if (EQUAL_ANY(in->argv[i-1], "-D", "-U", "-x", "-aux-info", "-dumpbase", "-auxbase",
				"-I", "-u", "-T", "--param", "-G", "-MF", "-MD", "-MMD")
			|| HAS_PREFIX(in->argv[i-1], "-X")
			|| (HAS_PREFIX(in->argv[i-1], "-i") && HAS_PREFIX_ANY(in->argv[i-1], "-ia", "-ib", "-ic", "-id", "-ie", "-if", "-ig", "-ih", "-ii", "-ij", "-ik", "-il", "-im", "-in", "-io", "-ip", "-iq", "-ir", "-is", "-it", "-iu", "-iv", "-iw", "-ix", "-iy", "-iz"))
			)
			{
				// it's the option's argument
			}
			else
			{
				// it may be an input file
				APPEND3(res->infiles_count, res->infiles_names, in->argv[i]);
			}
		}
		debug_println(2, "Normalize: snarfing %s", in->argv[i]);
		APPEND(out, in->argv[i]);
	} // end for i
	// re-add -o
	if (res->saw_o)
	{
		APPEND(out, "-o");
		APPEND(out, *(res->saw_o + 1));
	}
	// if we saw -Os and -Werror and -D_FORTIFY_SOURCE, then we have a problem:
	// -Os adds a builtin #define of _FORTIFY_SOURCE which triggers a multiple
	// definition warning, hence error. The integrated cpp avoids this, presumably
	// by detecting the already-present -D_FORTIFY_SOURCE. Arguably the client
	// is at fault, although it's not documented that -Os implies -D_FORTIFY_SOURCE.
	// HACK: if we saw all three, change -D_FORTIFY_SOURCE to -U_...
	if (res->saw_Os && res->saw_Werror && res->saw_D_FORTIFY_SOURCE)
	{
		// another HACK: to handle separate "-D" and "_FORTIFY_SOURCE", we only assume that
		// the pos records where the "-D" is
		if (EQUAL(out.argv[res->opos_D_FORTIFY_SOURCE], "-D"))
		{
			out.argv[res->opos_D_FORTIFY_SOURCE] = "-U";
			// rewrite the next one too
			char *found;
			if (NULL != (found = strchr(out.argv[res->opos_D_FORTIFY_SOURCE+1], '=')))
			{
				*found = '\0'; // HACK: here we in-place-update the input string
			}
		}
		else if (HAS_PREFIX(out.argv[res->opos_D_FORTIFY_SOURCE], "-D_FORTIFY_SOURCE"))
		{
			// HACK: here we in-place-update the input string *twice*
			out.argv[res->opos_D_FORTIFY_SOURCE][1] = 'U'; // change -D... to -U...
			char *found;
			if (NULL != (found = strchr(out.argv[res->opos_D_FORTIFY_SOURCE], '=')))
			{
				*found = '\0';
			}
		}
	}
	return out;
}

static void write_args(FILE *stream, struct args *args)
{
	for (int i = 0; i < args->argc; ++i)
	{
		fprintf(stream, "%s%s", (i != 0) ? " " : "", args->argv[i]);
	}
	fprintf(stream, "\n");
}
struct args lift_normalized_cc1_to_cc(struct args *in, char *driver, struct normalization_result *res)
{
	//debug_print 1 "writing cc options for $@" 1>&2
	if (debug_level >= 1)
	{
		fprintf(debug_stream?:stderr, "writing cc options for ");
		write_args(debug_stream?:stderr, in);
	}
	struct args out = { .argc = 0 };
	APPEND(out, driver);
	for (unsigned i = 1; i < in->argc; ++i)
	{
		debug_println(2, "args remaining %d, argv[i] is `%s'", in->argc - i, in->argv[i]);
		// we are running our own .i-to-.s pass -- filter out cpp-only args
		if (EQUAL_ANY(in->argv[i], "-imultiarch", "-triple", "-main-file-name", "-ferror-limit", "-target-cpu", "-tune-cpu", "-mrelocation-model")
				|| HAS_PREFIX_ANY(in->argv[i], "-iremap", "-internal-"))
		{
			// skip the arg too
			++i;
		}
		else if (EQUAL_ANY(in->argv[i], "-quiet", "-fhonour-copts", "-mframe-pointer=all",
				"-mconstructor-aliases", "-munwind-tables", "-disable-free", "-disable-llvm-verifier",
				"-discard-value-names")
			||  HAS_PREFIX(in->argv[i], "-debugger-tuning="))
		{
			// skip just it
			continue;
		}
		else if (EQUAL(in->argv[i], "-traditional-cpp"))
		{
			if (not_really_traditional) continue;
			debug_println(0, "Really traditional!");
		}
		else if (EQUAL(in->argv[i], "-cc1"))
		{
			continue; // we are clang, but we want to write a cc command
		}
		else if (EQUAL_ANY(in->argv[i], "-MD", "-MMD"))
		{
			// NASTY: with cc1, -MD has an argument! it's the filename, like with -MF.
			// with cc or cpp, we have to use -MM?D -MF
			APPEND(out, in->argv[i]);
			APPEND(out, "-MF");
			if (i+1 >= in->argc) die("-MD or -MMD as last argument");
			APPEND(out, in->argv[i+1]); // the filename argument
		}
		else
		{
			debug_println(2, "Write-cc: snarfing %s", in->argv[i]);
			APPEND(out, in->argv[i]);
		}
	}
	return out;
}

#undef APPEND  /* to avoid confusion with APPEND_ONE which we define later */ 

_Bool cc1_command_is_pp(struct args *in)
{
	if (debug_level >= 2)
	{
		fprintf(debug_stream?:stderr, "is pp? ");
		write_args(debug_stream?:stderr, in);
	}
	char **saw_E = NULL;
	char **saw_o = NULL;
	char **saw_M_MM = NULL;
	_Bool ret;
	for (unsigned i = 1; i < in->argc; ++i)
	{
		if (EQUAL(in->argv[i], "-o")) { saw_o = &in->argv[i]; continue; }
		if (EQUAL_ANY(in->argv[i], "-M", "-MM"))  { saw_M_MM = &in->argv[i]; continue; }
		if (EQUAL(in->argv[i], "-E")) { saw_E = &in->argv[i]; continue; }
	}
	// If we didn't see an output file, it might mean that
	// - the default output filename is being used (DOES the driver do this?)
	// - the output is going to stdout, and it's a make rule (-M, -MM)
	// - the output is actual compilation stuff and -pipe is being used?
	// FIXME: support this case once we've seen an example.
	if (!saw_o && !saw_M_MM) die("FIXME: can't work with cc1/cc1plus commands with no output file");
	if (!saw_E)
	{
		debug_println(1, "Wrapping cc1, we don't seem to be doing preprocessing");
		ret = 0;
	}
	else
	{
		debug_println(1, "Wrapping cc1, we seem to be doing a preprocessing step"); 
		ret = 1;
	}
	return ret;
}

struct args get_cc_options_from_cc1_command(struct args *in, char *driver)
{
	struct normalization_result res; bzero(&res, sizeof res);
	struct args norm = normalize_cc1_argv(in, &res);
	return lift_normalized_cc1_to_cc(&norm, driver, &res);
}

const char *parse_escape_sequence(const char *pos, char *out)
{
	assert(pos[-1] == '\\');
	switch (pos[0])
	{
		case '\0': return pos;
		case '0':  /* parse an octal number */ assert(0 && "octal escapes unimplemented");
		case 'x':  /* parse a hex number */    assert(0 && "hex escapes unimplemented");
		default: *out = pos[0]; return pos + 1;
	}
}
/* XXX: this is close to what wordexp() can do for us, but not quite... it does too much!
 * Possibly we should use it anyway, though? */
struct args parse_shell_quoted_line_as_argv(const char *line)
{
	/* Hmm. Is there a libc function that can help us? I don't think so.
	 * We need to read lines in the form in which they appear in the output of cc -###.
	 * This uses quotes.
	 * Does it also use backslash-escapes? Yes, it can do, e.g. a file called '"hello world".c'.
	 */
	_Bool in_double_quotes = 0;
	_Bool in_single_quotes = 0;
	char *current_word = NULL;
	char *current_word_pos;
	struct args out = { .argc = 0, .argv = NULL };
#define APPEND_ONE(c) do { \
	if (!current_word) { current_word = /* worst case */ calloc(1, remaining_len + 1); current_word_pos = current_word; } \
	*current_word_pos++ = c; \
} while (0)
#define FINISH_WORD() do { \
	if (!current_word) current_word = calloc(1, 1); \
	/* fprintf(stderr, "out.argv PRE is %p (size %ld, argc %d)\n", out.argv, out.argv ? (long) malloc_usable_size(out.argv) : (long) 0, out.argc); */ \
	out.argv = realloc(out.argv, (1 + ++out.argc) * sizeof (char*)); \
	debug_println(1, "out.argv POST is %p", out.argv); \
	if (!out.argv) die("could not allocate memory ()"); \
	current_word = realloc(current_word, strlen(current_word) + 1); /* shrink it!*/ \
	/* if argc==0, we have no elements in argv. But we always have at least one. */ \
	out.argv[out.argc - 1] = current_word; \
	out.argv[out.argc] = NULL; \
	/* fprintf(stderr, "out.argv REALLYPOST is %p (size %ld)\n", out.argv, out.argv ? (long) malloc_usable_size(out.argv) : (long) 0); */ \
	current_word = NULL; \
	current_word_pos = NULL; \
} while (0)
	const char *p = line;
	size_t len = strlen(line);
	size_t remaining_len = len;
	char c;
	while ('\0' != (--remaining_len, c = *p++))
	{
		if (isspace(c) && !in_double_quotes && !in_single_quotes)
		{
			/* If we're in a word, finish it here. */
			if (current_word) FINISH_WORD();
			/* then gobble spaces, i.e. do nothing */
		}
		else switch (c)
		{
			case '\\': {
				/* process the whole escape sequence in one go? we could realloc the  */
				char the_c_unescaped;
				const char *nextpos = parse_escape_sequence(p, &the_c_unescaped);
				if (nextpos != p) APPEND_ONE(the_c_unescaped);
				p = nextpos; /* i.e. skip forward */
			}	break;
			case '\'': if (!in_double_quotes) { in_single_quotes ^= 1; } else APPEND_ONE(c); break;
			case '"':  if (!in_single_quotes) { in_double_quotes ^= 1; } else APPEND_ONE(c); break;
			default: APPEND_ONE(c); break;
		}
	}
	if (current_word) { FINISH_WORD(); }
	return out;
}
static pid_t the_pid; // HACK
/* HACK: we implement our own popen()-alike where the argument vector
 * is explicit, as opposed to serialized into a command string for /bin/sh.
 * This is a little fraught. */
FILE *popen_argv_for_reading(int argc, char **argv)
{
	int fds[2];
	FILE *f = NULL;
	if (pipe2(fds, O_CLOEXEC)) return NULL;

	/* fork and exec */
	int pid = fork();
	if (pid == -1)
	{
		/* failure */
		goto out;
	}
	if (pid == 0)
	{
		/* child: write to the write end of the pipe; stderr goes to stdout */
		dup2(fds[1], 1);
		dup2(fds[1], 2);
		execve(argv[0], argv, environ);
		/* failed */
		err(EXIT_FAILURE, NULL);
	}
	else
	{
		/* remember the PID (hack!) */
		the_pid = pid;
		/* parent */
		f = fdopen(fds[0], "r");
		/* close the write end of the pipe, so that only the child has it open */
		close(fds[1]);
		/* do we need to wait? no, do it in pclose() */
	}
out:
	if (!f) { close(fds[0]); close(fds[1]); return NULL; }
	return f;
}
void pclose_argv(FILE *f /* ignored! */)
{
	/* GAH. How do we know the PID? We need to stash it somewhere
	 * but we can't. musl's FILE has a field called pipe_pid.
	 * We just use a static global variable for now. */
	int wstatus, ret;
	while (-EINTR == (ret = wait4(the_pid, &wstatus, 0, NULL))) {}
}
#define realloca_argv_with_prefix(argc, argv, pre_argc, pre_argv) \
({ \
	char **new_argv = alloca((argc + pre_argc + 1) * sizeof (char*)); \
	memcpy(new_argv, pre_argv, pre_argc * sizeof (char*)); \
	memcpy(new_argv + pre_argc, argv, (argc + /* include NULL */ 1) * sizeof (char*)); \
	new_argv; \
})
// ---------------------------------
struct command_and_terminator {
	struct args args;
	_Bool ends_with_pipe;
};
static _Bool iterate_commands(struct command_and_terminator *commands, unsigned ncommands,
	_Bool (*cb)(struct command_and_terminator *, void *), void *arg)
{
	for (unsigned i_cmd = 0; i_cmd < ncommands; ++i_cmd)
	{
		_Bool carry_on = cb(&commands[i_cmd], arg);
		if (!carry_on) return 0;
	}
	return 1;
}

static void print_command_args(FILE *stream, struct args *args)
{
	for (unsigned i_word = 0; i_word < args->argc; ++i_word)
	{
		if (i_word != 0) fprintf(stderr, " ");
		// FIXME: quote shell, protect from word-splitting
		fprintf(stream, "%s", args->argv[i_word]);
	}
}
static _Bool print_command(struct command_and_terminator *cmd, void *stream_as_void)
{
	FILE *stream = stream_as_void;
	fprintf(stream, " ");
	print_command_args(stream, &cmd->args);
	if (cmd->ends_with_pipe)
	{
		fprintf(stream, " |");
	}
	fprintf(stream, "\n");

	return 1;
}

static int input_fd = -1;
static _Bool rewrite_and_run_command(struct command_and_terminator *cmd, void *driver_pathname_as_void)
{
	// debugging
	if (debug_level >= 1) print_command(cmd, debug_stream?:stderr);
	// now the real stuff
	char *driver_pathname = driver_pathname_as_void;
	struct args the_cmd;
	debug_println(1, "basename is %s", basename(cmd->args.argv[0]));
	if (EQUAL_ANY(basename(cmd->args.argv[0]), "cc1", "cc1plus", "clang")
		&& cc1_command_is_pp(&cmd->args))
	{
		char *driver_args[] = { driver_pathname, "-E", NULL };
		struct args pp_cmd_args = get_cc_options_from_cc1_command(&cmd->args, driver_pathname);
		the_cmd = (struct args) {
			.argv = realloca_argv_with_prefix(pp_cmd_args.argc - 1, pp_cmd_args.argv + 1, 2, driver_args),
			.argc = pp_cmd_args.argc - 1 + 2
		};
	}
	else if (EQUAL_ANY(basename(cmd->args.argv[0]), "cc1", "cc1plus", "clang"))
	{
		// non-pp case
		char *driver_args[] = { driver_pathname, "-S", NULL };
		struct args non_pp_cmd_args = get_cc_options_from_cc1_command(&cmd->args, driver_pathname);
		the_cmd = (struct args) {
			.argv = realloca_argv_with_prefix(non_pp_cmd_args.argc - 1, non_pp_cmd_args.argv + 1, 2, driver_args),
			.argc = non_pp_cmd_args.argc - 1 + 2
		};
	}
	else
	{
		the_cmd = cmd->args;
	}
	if (debug_level >= 1)
	{
		fprintf(debug_stream?:stderr, "BECOMES... ");
		print_command_args(debug_stream?:stderr, &the_cmd);
		fprintf(debug_stream?:stderr, "\n");
	}
	int maybe_our_input = input_fd;
	int maybe_our_output;
	/* We may have to pipe the output onwards */
	int the_pipe[2] = { -1, -1 };
	if (cmd->ends_with_pipe)
	{
		/* open a pipe */
		int ret = pipe(the_pipe);
		if (ret != 0) err(EXIT_FAILURE, "opening pipe");
		// leave the read end for the next command around the loop
		maybe_our_output = the_pipe[1];
		input_fd = the_pipe[0];
	}
	else
	{
		maybe_our_output = -1;
		input_fd = -1; /* what we leave for the next iteration;
			we've snarfed *our* input fd, if any, as 'maybe_our_input' */
	}
	/* We should now have our command to run. We may have an fd
	 * to read from as stdin, or not, and one to write as stdout, or not. */
	pid_t p = fork();
	if (p == -1) err(EXIT_FAILURE, "forking");
	if (p == 0)
	{
		/* we are the child */
		int ret;
		if (maybe_our_input != -1)  { ret = dup2(maybe_our_input, 0);  if (ret == -1) err(EXIT_FAILURE, "input dup");  }
		assert(maybe_our_output != 1);
		if (maybe_our_output != -1) { ret = dup2(maybe_our_output, 1); if (ret == -1) err(EXIT_FAILURE, "output dup from %d (pid %d, about to exec %s)", maybe_our_output, (int) getpid(), the_cmd.argv[0]); }
		ret = (strchr(the_cmd.argv[0], '/') ? execve : execvpe)(
				the_cmd.argv[0], the_cmd.argv, environ
			);
		err(EXIT_FAILURE, "execve() returned %d", ret);
	}
	else
	{
		/* we are the parent; we have no need for those pipe ends now, so
		 * we'd like to close them, but if we do, our input dup fails. why?
		 * The child's copy of the file descriptor should be distinct.
		 * For now just close the writing end. That seems to be OK. */
		if (the_pipe[0] != -1) 
		{
			assert(the_pipe[1] != -1);
			//close(the_pipe[0]);
			close(the_pipe[1]);
		} else assert(the_pipe[1] == -1);
		/* do we wait for this one or keep going? */
		if (!cmd->ends_with_pipe)
		{
			int wstatus;
			pid_t w;
			do {
				w = waitpid(p, &wstatus, WUNTRACED | WCONTINUED);
				if (w == -1) {
					err(EXIT_FAILURE, "waitpid");
				}
				if (WIFEXITED(wstatus)) {
					debug_println(1, "child exited, status %d", (int) WEXITSTATUS(wstatus));
				} else if (WIFSIGNALED(wstatus)) {
					debug_println(0, "child killed by signal %d", (int) WTERMSIG(wstatus));
				}
			} while (!WIFEXITED(wstatus) && !WIFSIGNALED(wstatus));
			if (WIFSIGNALED(wstatus)) exit(2);
			if (0 != WEXITSTATUS(wstatus)) exit(1);
		}
		else
		{
			// just continue... we may need to fork a command that consumes the output
		}
	}
	return 1; // keep going
}

int main(int argc, char **argv)
{
	char *debug_var;
	if (NULL != (debug_var = getenv("DEBUG_CC")))
	{
		debug_level = atoi(debug_var);
		debug_stream = stderr;
	}
	int exit_status; // no init; compiler will warn if we use uninit'd along any path
	if (argc < 2) die("must give a compiler command to wrap");
	char *driver_arg = argv[1]; // chomp the driver name

	unsigned driver_argv_count = 1;
	char **driver_argv_strings = malloc(sizeof (char**));
	if (!driver_argv_strings) die("could not allocate memory (argv vec)");
	driver_argv_strings[0] = driver_arg; // we may append more

	char *driver_pathname = NULL;
	if (strchr(driver_arg, '/')) driver_pathname = driver_arg;
	else
	{
		/* The driver is not named by an absolute (/...) or CWD-relative (e.g. ./) path,
		 * but simply by something that needs PATH-based resolution. We have to do this
		 * ourselves, but we cheat: use 'which' in the '//' line at the very top of the
		 * file. So we should never reach this. */
		errx(EXIT_FAILURE, "internal error: driver command is not a pathname (see 'which' on top line)");
	}
	char *driver_realpath = realpath(driver_pathname, NULL);
	if (!driver_realpath) die("driver does not exist?!");
	char *driver_realpath_basename = basename(driver_realpath);
	char *found;
	if (NULL != (found = strstr(driver_realpath_basename, "gcc")))
	{
		APPEND3(driver_argv_count, driver_argv_strings, "-no-integrated-cpp");
	}
	else if (NULL != (found = strstr(driver_realpath_basename, "clang")))
	{
		APPEND3(driver_argv_count, driver_argv_strings, "-traditional-cpp");
		// FIXME: only set not_really_traditional if -traditional-cpp is not present in args
		not_really_traditional = 1; // we will skip -traditional-cpp when writing cc args
	}
	APPEND3(driver_argv_count, driver_argv_strings, "-###");
	free(driver_realpath);
	driver_realpath = NULL;

	// get the subcommand lines that the driver wants to run
	struct args prefixed = {
		.argv = realloca_argv_with_prefix(argc - 2, argv + 2, driver_argv_count, driver_argv_strings),
		.argc = argc - 1 + driver_argv_count
	};
	FILE *lines = popen_argv_for_reading(prefixed.argc, prefixed.argv);
	ssize_t nread;
	size_t len = 0;
	char *the_line_allocated = NULL;
	struct command_and_terminator *commands = NULL; // an array of commands, initially 0 of them
	unsigned commands_count = 0;
	do
	{
		len = 0;
		/* PROBLEM: getline() may hang, e.g. if the child process is defunct.
		 * Actually, is that the problem? If I hack in the 'wait' below, then
		 * the defunct child process successfully exits, but getline() still
		 * hangs. */
		nread = getline(&the_line_allocated, &len, lines);
		debug_println(1, "nread was %d", (int) nread);
		assert(the_line_allocated);
		if (nread != -1)
		{
			/* we have got a line; we care only about those beginning with ' ' */
			if (!(nread >= 1 && the_line_allocated[0] == ' ')) goto next;
			/* we have got a line beginning with ' '... it is shell-quoted */
			commands = realloc(commands, ++commands_count * sizeof *commands);
			if (!commands) die("could not allocate memory (commands vector)");
			struct command_and_terminator *the_command = &commands[commands_count - 1];
			*the_command = (struct command_and_terminator) {
				.args = parse_shell_quoted_line_as_argv(the_line_allocated + 1 /* skip the space*/)
			};
			if (0 == strcmp(the_command->args.argv[the_command->args.argc - 1], "|"))
			{
				the_command->ends_with_pipe = 1;
				/* Drop the literal pipe token */
				the_command->args.argv[the_command->args.argc - 1] = NULL;
				the_command->args.argc--;
			}
		}
	next:
		free(the_line_allocated);
		the_line_allocated = NULL;
	} while (nread != -1 && nread != 0);
	pclose_argv(lines);

	/* We've read some commands; we should rewrite them. What's our strategy for that?
	 * Each command may be something we know how to
	 * scan              (chunk up the options; with CC_IDENTIFY_ARGS)
	 * rewrite-and-lift  (e.g. cilpp: $driver -E to a tempfile, then CIL to the intended output file)
	 *      -- above we do this by normalize_and_lift stuff
	 * just lift?
	 *
	 * RE-READ my blog post before going further. Re-read 'wrapper' also. */
	
	/* Then do we print them or run them? Do a linear scan of the driver options
	 * looking for '-###'. If we see it, print then exit. If we get to the end
	 * without seeing it, run them.
	 *
	 * XXX: we should only run them after doing a "default rewriting", which,
	 * for commands we recognise, means to lift them to single-function driver invocations.
	 * Use old-style lifting for now. If that results in a wrapper that performs well-ish,
	 * then it will be worth hte extra effort to .c-ify the clang/gcc-probing stuff.
	 * We already have the lifting code above!!!! So this should be easy. */
	exit_status = 0;
	for (unsigned i_driver_arg = 0; i_driver_arg < argc; ++i_driver_arg)
	{
		if (0 == strcmp(argv[i_driver_arg], "-###"))
		{
			iterate_commands(commands, commands_count, print_command, NULL);
			goto out;
		}
	}
	/* If we got here, we want to run the commands. We do a "default rewrite"
	 * for any that we recognise. The default rewrite is to lift to a single-function
	 * driver invocation. */
	exit_status = 1;
	_Bool success = iterate_commands(commands, commands_count, rewrite_and_run_command, driver_pathname);
	if (success) exit_status = 0;
out:
	return exit_status;
}
